on:
  pull_request:
  push:
    branches:
      - main
name: Lint check
jobs:
  check:
    name: check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v4
      - name: Runt Project Setup
        uses: ./.github/actions/setup
      - name: Test Code Lint
        run: |
          make check
          make mypy
